### ISSUE TITLE
Custom tag-name on custom elements (Green Core)

### ISSUE THREAD

**Issue by Maximilian-R** [seb-oss/green#1641]
### Description

Custom elements (Green Core) get a VER_SUFFIX added to them. Having an element name that changes over time does not play along nicely with some other tools.

Context: seb.se

For example Optimizely Experimentation (AB-tests). Their visual editor uses the tagname when selcting an element - which causes the test to fail in case we make a release that changes the version suffix during the test period.
 
We need to have the version suffix enabled to avoid conflicts with MFE:s using green, but we could perhaps work around the issue if we can specify a custom, but static version suffix. 
 
 Eg. `pw`, so `gds-button-4ffa29` becomes `gds-button-pw`

### Who will benefit from this feature?

Shell applications (seb.se)

**Comment by splashdust** [comment]
An alternative which should be possible since 1.44.0 is to re-register a subclass under a different name. Like this:

```js
// Create a subclass of a Gds component
class MyButton extends GdsButton {}

// Register under a custom name
window.customElementRegistry.define("my-button", MyButton);
```

Not as seamless as a custom suffix since it would need to be done for each used component, but on the other hand offers more granularity.

What's your thoughts on this approach?

**Comment by Maximilian-R** [comment]
Cool, at this moment the need is mainly for buttons, so this could work fine! 😄👍

**Comment by splashdust** [comment]
I'm closing this one now, since it seems like the custom registration solved the problem.

One addendum to the targeting concerns though, is that there are some places in the code that checks if a slotted element name starts with `gds`. This is necessary in some cases, since the `[gds-element]` attribute won't exist until the slotted child has initialized. So as a best practice, it would be safest to only change the suffix of the name.

So:
- Don't: `xyz-button`
- Do: `gds-button-xyz`
