### ISSUE TITLE
Dropdown: Unrestrictive styling

### ISSUE THREAD

**Issue by vizorian** [seb-oss/green#1836]
### Description

It would be great to have the ability to style Dropdown component completely. Currently, the issue is that some parts of this component is styled via Shadow-DOM, thus making it impossible.

E.g. I wanted to have a Dropdown, which can be validated as any other input, with visuals to match:
![image](https://github.com/user-attachments/assets/7360575e-5d0e-48e6-ad55-6083fc089ff3)

This is unachievable neither by providing errors to the Dropdown, neither by applying custom styling, as it's styled via shadow-root:
![image](https://github.com/user-attachments/assets/549feece-3adf-4828-b682-d8319b54dabb)

### Who will benefit from this feature?

Leasing team & anyone else who wants to customize the Dropdown.

**Comment by EldRoos** [comment]
I did not understand, what is current dropdown missing/different from what you want? (if you don't count the openness of free styling)

**Comment by splashdust** [comment]
The reason the components use shadow dom is twofold:
- Provide style encapsulation to protect against conflicts which often occurs in a micro-frontend environment
- Put constraints on the design itself. When a feature is missing, it is important that it is implemented in the components and designed according to brand guidelines and so on. If every team/developer add their own tweaks, consistency goes out the window.

In this particular case, the style you are looking for is already implemented in the component. If you use it directly from the Core library, it is triggered by setting the `invalid` property to true. If you are using it through the React wrapper, it is still done through a legacy method used by the form components in React.

It looks something like this:
```tsx
const validatorError = {
  message: 'This field is required',
  indicator: 'error',
}

...

<Dropdown
  label={'Label'}
  options={dropdownOptions}
  validator={validator}
/>
```

There's a full form example for React available here, if you wanna peek at it: https://github.com/seb-oss/green/blob/main/apps/react-lib-dev/src/app/form.tsx

Closing this issue now, since we will not remove shadow dom in the core components, but if you need additional help with this issue, feel free to reach out on Teams!

**Comment by vizorian** [comment]
Thanks, I'll give it a go
